version: '3'
services:
  frontend:
    image: ozgurozturknet/fe:proje
    ports:
      - "3000:80"
    # Add any additional configuration for service1 here

  backend:
    image: ozgurozturknet/be:proje
    ports:
      - "5000:80"
    # Add any additional configuration for service2 here

  database:
    image: ozgurozturknet/db:proje
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=todo_admin
      - MYSQL_PASSWORD=password
    # Add any additional configuration for service3 here